### ISSUE TITLE
Enlarge the area of draggable elements.

### ISSUE THREAD

**Issue by Aidyl98** [Root-101/citmatel_strawberry_dnd#12]
Enlarge the area by which the list of draggable elements is grabbed. It is very difficult to select between the elements to move the widget left or right if you don't want to select the middle one.

**Comment by JesusHdezWaterloo** [comment]
aumentar en `dnd_sublevel_screen/_buildDraggableItemList()` el argumento `viewportFraction: 0.25,`

**Comment by JesusHdezWaterloo** [comment]
Agrandada la distancia al 40% `viewportFraction: 0.4,`
